<a href="https://colab.research.google.com/github/Limm-jk/2020_Fall_MachineLearning/blob/master/Mnist_MLP_sklearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
from mlxtend.data import loadlocal_mnist
from sklearn.neural_network import MLPClassifier

X, y = loadlocal_mnist(images_path='/content/drive/My Drive/Colab Notebooks/train-images.idx3-ubyte', labels_path='/content/drive/My Drive/Colab Notebooks/train-labels.idx1-ubyte')
y.reshape(60000,1)
print(X.shape)
print(y.shape)

(60000, 784)
(60000,)


In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,y,test_size=0.4)
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test)
print(Y_test[1].dtype)

(36000, 784)
(24000, 784)
(36000,)
[8 2 8 ... 1 5 1]
uint8


In [54]:
mlp_100 = MLPClassifier(solver='lbfgs', random_state = 0, hidden_layer_sizes=[100])
mlp_100.fit(X_train,Y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(100,), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=200,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [50]:
print('테스트 셋 정확도 : {: .3f}'.format(mlp_100.score(X_test, Y_test)))
print('트레이닝 셋 정확도 : {: .3f}'.format(mlp_100.score(X_train, Y_train)))

테스트 셋 정확도 :  0.123
트레이닝 셋 정확도 :  0.117


In [ ]:
mlp_1010 = MLPClassifier(solver='lbfgs', random_state = 0, hidden_layer_sizes=[10,10])
mlp_1010.fit(X_train,Y_train)

In [20]:
print('테스트 셋 정확도 : {: .3f}'.format(mlp_1010.score(X_test, Y_test)))
print('트레이닝 셋 정확도 : {: .3f}'.format(mlp_1010.score(X_train, Y_train)))

테스트 셋 정확도 :  0.360
트레이닝 셋 정확도 :  0.367


In [21]:
mlp_303030 = MLPClassifier(solver='lbfgs', random_state = 0, hidden_layer_sizes=[30,30,30])
mlp_303030.fit(X_train,Y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:470: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=[30, 30, 30], learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=200,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=0, shuffle=True, solver='lbfgs',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [22]:
print('테스트 셋 정확도 : {: .3f}'.format(mlp_303030.score(X_test, Y_test)))
print('트레이닝 셋 정확도 : {: .3f}'.format(mlp_303030.score(X_train, Y_train)))

테스트 셋 정확도 :  0.754
트레이닝 셋 정확도 :  0.755


In [30]:
mean_train = X_train.mean(axis=0)
std_train = X_train.std(axis=0)
X_train_s = (X_train-mean_train)/std_train
X_train_s = np.nan_to_num(X_train_s)
X_test_s = (X_test-mean_train)/std_train
X_test_s = np.nan_to_num(X_test_s)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in true_divide
  """
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in true_divide
  """


In [45]:
mlp_100.fit(X_train_s,Y_train)
mlp_1010.fit(X_train_s,Y_train)
mlp_303030.fit(X_train_s,Y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:470: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=[30, 30, 30], learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=200,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=0, shuffle=True, solver='lbfgs',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [46]:
print('[100]테스트 셋 정확도 : {: .3f}'.format(mlp_100.score(X_test_s, Y_test)))
print('[100]트레이닝 셋 정확도 : {: .3f}'.format(mlp_100.score(X_train_s, Y_train)))
print('[10 10]테스트 셋 정확도 : {: .3f}'.format(mlp_1010.score(X_test_s, Y_test)))
print('[10 10]트레이닝 셋 정확도 : {: .3f}'.format(mlp_1010.score(X_train_s, Y_train)))
print('[30 30 30]테스트 셋 정확도 : {: .3f}'.format(mlp_303030.score(X_test_s, Y_test)))
print('[30 30 30]트레이닝 셋 정확도 : {: .3f}'.format(mlp_303030.score(X_train_s, Y_train)))

/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py:90: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)


[100]테스트 셋 정확도 :  0.964
[100]트레이닝 셋 정확도 :  1.000
[10 10]테스트 셋 정확도 :  0.915


/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py:90: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)


[10 10]트레이닝 셋 정확도 :  0.975
[30 30 30]테스트 셋 정확도 :  0.953


/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py:90: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_base.py:92: RuntimeWarning: overflow encountered in subtract
  tmp = X - X.max(axis=1)[:, np.newaxis]


[30 30 30]트레이닝 셋 정확도 :  1.000


In [51]:
mlp_100_it = MLPClassifier(solver='lbfgs', max_iter=1000,random_state = 0, hidden_layer_sizes=[100])
mlp_1010_it = MLPClassifier(solver='lbfgs',max_iter=1000, random_state = 0, hidden_layer_sizes=[10,10])
mlp_303030_it = MLPClassifier(solver='lbfgs',max_iter=1000, random_state = 0, hidden_layer_sizes=[30,30,30])

In [47]:
mlp_100 = MLPClassifier(solver='lbfgs',random_state = 0, hidden_layer_sizes=[100])
mlp_1010 = MLPClassifier(solver='lbfgs', random_state = 0, hidden_layer_sizes=[10,10])
mlp_303030 = MLPClassifier(solver='lbfgs', random_state = 0, hidden_layer_sizes=[30,30,30])

In [42]:
mlp_100_it.fit(X_train,Y_train)
mlp_1010_it.fit(X_train,Y_train)
mlp_303030_it.fit(X_train,Y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:470: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:470: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=[30, 30, 30], learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=1000,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=0, shuffle=True, solver='lbfgs',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [43]:
print('[100]테스트 셋 정확도 : {: .3f}'.format(mlp_100_it.score(X_test, Y_test)))
print('[100]트레이닝 셋 정확도 : {: .3f}'.format(mlp_100_it.score(X_train, Y_train)))
print('[10 10]테스트 셋 정확도 : {: .3f}'.format(mlp_1010_it.score(X_test, Y_test)))
print('[10 10]트레이닝 셋 정확도 : {: .3f}'.format(mlp_1010_it.score(X_train, Y_train)))
print('[30 30 30]테스트 셋 정확도 : {: .3f}'.format(mlp_303030_it.score(X_test, Y_test)))
print('[30 30 30]트레이닝 셋 정확도 : {: .3f}'.format(mlp_303030_it.score(X_train, Y_train)))

[100]테스트 셋 정확도 :  0.123
[100]트레이닝 셋 정확도 :  0.117
[10 10]테스트 셋 정확도 :  0.425
[10 10]트레이닝 셋 정확도 :  0.423
[30 30 30]테스트 셋 정확도 :  0.907
[30 30 30]트레이닝 셋 정확도 :  0.933


In [52]:
mlp_100_it.fit(X_train_s,Y_train)
mlp_1010_it.fit(X_train_s,Y_train)
mlp_303030_it.fit(X_train_s,Y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:470: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=[30, 30, 30], learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=1000,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=0, shuffle=True, solver='lbfgs',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [53]:
print('[100]테스트 셋 정확도 : {: .3f}'.format(mlp_100_it.score(X_test_s, Y_test)))
print('[100]트레이닝 셋 정확도 : {: .3f}'.format(mlp_100_it.score(X_train_s, Y_train)))
print('[10 10]테스트 셋 정확도 : {: .3f}'.format(mlp_1010_it.score(X_test_s, Y_test)))
print('[10 10]트레이닝 셋 정확도 : {: .3f}'.format(mlp_1010_it.score(X_train_s, Y_train)))
print('[30 30 30]테스트 셋 정확도 : {: .3f}'.format(mlp_303030_it.score(X_test_s, Y_test)))
print('[30 30 30]트레이닝 셋 정확도 : {: .3f}'.format(mlp_303030_it.score(X_train_s, Y_train)))

/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py:90: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)


[100]테스트 셋 정확도 :  0.964
[100]트레이닝 셋 정확도 :  1.000
[10 10]테스트 셋 정확도 :  0.888


/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py:90: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/extmath.py:151: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_base.py:92: RuntimeWarning: overflow encountered in subtract
  tmp = X - X.max(axis=1)[:, np.newaxis]
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_base.py:92: RuntimeWarning: invalid value encountered in subtract
  tmp = X - X.max(axis=1)[:, np.newaxis]


[10 10]트레이닝 셋 정확도 :  0.999
[30 30 30]테스트 셋 정확도 :  0.953


/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py:90: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_base.py:92: RuntimeWarning: overflow encountered in subtract
  tmp = X - X.max(axis=1)[:, np.newaxis]


[30 30 30]트레이닝 셋 정확도 :  1.000
